### ISSUE TITLE
1.16.x Update Progress

### ISSUE THREAD

**Issue by OhTheDungeon** [OhTheDungeon/OhTheDungeon#1]
**NBT Update**
- [x] Firework NBT
- [x] Armour NBT
- [x] Spawner NBT
- [x] JsonToNBT

**Spigot API Update**
- [x] New Biomes Injection
- [x] New EntityType Injection

**Async World Gen**
- [ ] Async Roguelike Generator (freeze)
- [ ] Half-Async Doomlike Generator (freeze)

**System Rewrite**
- [x] Loot System Rewrite
- [ ] Dungeon Theme Selector
- [x] WeightedRandomLoot

**Translation**
- [x] 中文翻译版
- [x] Translation Cooperation Platform

**Official API**
- [x] Event System

**Comment by chagohunt** [comment]
cheer up 
i love this plugin

**Comment by landhaurum** [comment]
Excited for the update. Great plugin!

**Comment by AnonAlpha** [comment]
If you can make a language file, I can translate it into Chinese

**Comment by kurosaki-haku** [comment]
Looking forward to 1.16 update!
