### ISSUE TITLE
Loot Not in Chests

### ISSUE THREAD

**Issue by nanohard** [OhTheDungeon/OhTheDungeon#1]
Greetings.
I have created loot successfully, but cannot get all loot boxes to contain at least one item; whether it's from my custom loot or not I do not care, I'm just trying to prevent any empty chests.
I've tried both settings of using Custom Loot true/false, but have only ever found all loot in one chest, the rest are empty. I'm still attempting to test to see if I can get it to work, it may be a PEBKAC issue, not sure.

**Comment by OhTheDungeon** [comment]
Did you turn off the built-in loot?

**Comment by DereC4** [comment]
There's an option asking to enable or disable built in loot. Take a look at it for each dungeon.
