### ISSUE TITLE
Question: Is there a way too disable players from being able to /otd_tp?

### ISSUE THREAD

**Issue by Extravent3** [OhTheDungeon/OhTheDungeon#12]
In a server I own, players are able to do /otd_tp and teleport to a dungeon. Now this would be fine if some didn't abuse this command. I and my Server Manager couldn't figure out how too disable the command. 

So if you could provide insight on if this is possible or not please let me know. Thanks.

**Comment by OhTheDungeon** [comment]
PLEASE READ https://github.com/OhTheDungeon/OhTheDungeon/blob/main/OTD.pdf

It has said the permission of `/otd_tp`
