### ISSUE TITLE
Internal Error happening when trying to put down a dungeon using commands

### ISSUE THREAD

**Issue by VCR505** [OhTheDungeon/OhTheDungeon#14]
Please help all it says is this everytime I want to put a dungeon down

<html>
<body>

[20:07:52] [Server thread/ERROR]: null
--
  | org.bukkit.command.CommandException: Unhandled exception executing command 'otd_place' in plugin Oh_the_dungeons_youll_go v15.3
  | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1936) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1779) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1732) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
  | Caused by: java.lang.NullPointerException
  | at org.bukkit.craftbukkit.v1_16_R3.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:502) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.getBiome(CraftWorld.java:942) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.getBiome(CraftWorld.java:937) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | at otd.dungeon.draylar.BattleTowerSchematics.place(BattleTowerSchematics.java:215) ~[?:?]
  | at otd.commands.Otd_Place.onCommand(Otd_Place.java:140) ~[?:?]
  | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
  | ... 19 more

</body>
</html>

**Comment by OhTheDungeon** [comment]
It seems you are using some datapacks to defined custom biome.
Spigot currently doesn't support that. So you need to remove those datapack

https://hub.spigotmc.org/jira/browse/SPIGOT-6073
