### ISSUE TITLE
Turning off PerPlayerDungeonInstance

### ISSUE THREAD

**Issue by OverBrave** [OhTheDungeon/OhTheDungeon#16]
I think there is no setting to turn off this feature in the plugin and it creates a special world just because of this feature. Can you add settings for this?

**Comment by OverBrave** [comment]
Why was the issue closed? Will you add it in the next update?

**Comment by OhTheDungeon** [comment]
Use permission node to revoke `/otd_pi` for normal user

**Comment by OverBrave** [comment]
I know how to disable player teleport to PlayerDungeons world. I need fully disable this feature from server. Because plugin creating extra world for this.

**Comment by OhTheDungeon** [comment]
I already explain why we need that world in the thread of spigot.

1. After 1.17, this world is needed to fix async generation issue for roguelike type (especially for NBT binding)
2. This world is needed for 3D biome algorithm
3. This world is needed for 1.18, as the average terrain height is higher, which will cause trouble for roguelike generation

Unless, I won't let people get a premium plugin for free. I hope this is perfectly clear

**Comment by OverBrave** [comment]
Thank you for your explanation.

I guess I didn't see that thread.
The extra world created is from 1.17. Should I delete it and have it recreate according to 1.18?

Or can it stay as it is?

**Comment by OhTheDungeon** [comment]
Sorry I'm confused...
> I guess I didn't see that thread.

Thread is where you download this mod

> The extra world created is from 1.17. Should I delete it and have it recreate according to 1.18?

Spigot release note has already explain everything for you. Check `World Upgrading`

**Comment by OverBrave** [comment]
Problem is, I'm not using the PerPlayerDungeonInstance plugin :D. Yes, now that plugin's page says this. This world is created even though I don't use this plugin. The only plugin I use is OTD.
