### ISSUE TITLE
I have trouble using command otd_place with custom structure

### ISSUE THREAD

**Issue by UniverseRealms** [OhTheDungeon/OhTheDungeon#18]
I can using this command but nothing happened. I was trying with .nbt file and schematic one but it cant generate it. It only shows me error in consol. It might be problem with software pupur but i dont know.
![Zrzut ekranu 2021-12-22 212953](https://user-images.githubusercontent.com/27692763/147151821-7cae232b-e265-45bd-9344-bcbac3671619.png)
l

**Comment by OhTheDungeon** [comment]
lack of info

**Comment by UniverseRealms** [comment]
Well after using newer version, custom structures wont generate and shows errors.

**Comment by UniverseRealms** [comment]
I think this says it can be problem with plugin itself.
