### ISSUE TITLE
Custom structures with *.nbt file

### ISSUE THREAD

**Issue by UniverseRealms** [OhTheDungeon/OhTheDungeon#20]
Custom structures only works with .schematic extansion, thats why im getting error when i want dungeon that have .nbt extansio
![Zrzut ekranu 2021-12-23 101015](https://user-images.githubusercontent.com/27692763/147230724-a86dcbd0-e8be-4a57-9bb3-4e7fd962202c.png)
n

**Comment by OhTheDungeon** [comment]
load and paste that with worldedit and see if that is success or not

**Comment by UniverseRealms** [comment]
Even worldedit wont coppy this in schematic folder.

**Comment by OhTheDungeon** [comment]
Then looks like it's some error in your NBT file(s).
Use schematic or scheme instead

Feel free to reopen this ticket if you find something

**Comment by UniverseRealms** [comment]
Alright

**Comment by UniverseRealms** [comment]
Oket so i was testing every possible file and. Plugin can't just place structure with .nbt and .schem extansion. Worldedit can only .schem and .schematic.
