### ISSUE TITLE
[Bug] Custom Structures

### ISSUE THREAD

**Issue by UniverseRealms** [OhTheDungeon/OhTheDungeon#21]
Custom structures won't load from extansion .nbt and .schem. Even worldedit won't paste the .nbt file structure.

**Comment by OhTheDungeon** [comment]
Test with standard schem/schematic files, all looking good

[OldNag]FloatingJungle.schem
[Zak561]FloatingTemple.schematic
[XTACx]KamiHouse1.schematic
[Jar9]FloatingSpawn[196x196].schem

https://i.imgur.com/Kr1akmO.png

**Comment by UniverseRealms** [comment]
I don't know why plugin won't work with .schem for me.
