### ISSUE TITLE
Sky-high towers / dungeon entrances

### ISSUE THREAD

**Issue by marcelschoen** [OhTheDungeon/OhTheDungeon#22]
On my 1.18.1 Paper server, I see towers (entrances to roguelike dungeons) like these everywhere:

![screenshot_otd](https://user-images.githubusercontent.com/1741855/147396279-d41247b8-e439-4fc7-ba11-b8a5ff65344e.png)

**Comment by OhTheDungeon** [comment]
Fixed in 15.11

**Comment by marcelschoen** [comment]
Great, thanks! Will test it right now.

**Comment by marcelschoen** [comment]
Yep, I can confirm that it works correctly now. Thanks again!
