### ISSUE TITLE
[question] player creates a random dungeon instance using sign

### ISSUE THREAD

**Issue by PappoYT** [OhTheDungeon/OhTheDungeon#26]
Sorry if this is not the right place for this kind of question but I didn't find any support Discord server.

Could be possible to let players create a random dungeon instance using sign?
Basically I would like to have the same thing as /otd_pi BUT no gui AND Terrain, Decoration and Tower Type are choose randomly each time.
TY

**Comment by OhTheDungeon** [comment]
We already provide command to create a dungeon.
And some other plugins like MyCommand could let you random some parameters by your need
