### ISSUE TITLE
[questions] world_config.json

### ISSUE THREAD

**Issue by PappoYT** [OhTheDungeon/OhTheDungeon#27]
**roguelike**
`"builtinLoot": true` > where can I find a list of the buildinLoot available? can I edit the list?
`"generous": true` > does this stand for Helpful Features option? can I edit the list of these items?

**loots**
`"weight": 1` > could you explain me how this works? it is 1 out 100? or 1 out the sum of all weights? or less means easy to find?
`"chance":` > what is the difference with `"weight":`? I cannot set this value, it is always 1.0
`"min": 6, "max": 6` > I cannot set min value, it is always the same as max value

**"example_otd"**
Can I remove this part from my config?

**Comment by OhTheDungeon** [comment]
`world_config.json` no longer exists after 15.13
