### ISSUE TITLE
Repository update request

### ISSUE THREAD

**Issue by steve4744** [OhTheDungeon/OhTheDungeon#29]
Please can you push the latest commits to the repo as it is currently 6 months out of date.

Or does Hu_XueJing have her own repo? In which case the link on the Spigot resource page needs to be updated to point to the new repo.

Thank you.

**Comment by OhTheDungeon** [comment]
We saw somebody who sold the updated version for 1.18 on ebay, which is really bad. We also saw somebody update their own plugins for their 1.18 server and they refused to make a pr here. These go against the original intention of this repo. So we decided to use Staggered update rule. When this mod updated to 1.19 version, we'll push the final 1.18 code

**Comment by steve4744** [comment]
Unfortunate, but neither of those scenarios is going to be prevented by not keeping the repo up to date. 

The result will be that genuine people who want to contribute to the project will be deterred from making a pr because the code base is so out of date.
