### ISSUE TITLE
[REQUEST] Allow reload config from world_config file

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [OhTheDungeon/OhTheDungeon#3]
Sometimes it's easier to edit the configuration in bulk by editing `world_config.json` instead of using the in game GUI, but as far as I know, there's no way to load the edited config from `world_config.json` after I edit the file so the changes doesn't get applied. Changing something with the in game GUI will override all changes made manually to `world_config.json`. The only way to apply the changes is to restart the server.

It would be nice if you add a command like `/otd reload` to reload config from `world_config.json`

**Comment by OhTheDungeon** [comment]
We never encourage users to modify configuration files.
