### ISSUE TITLE
Torches disable spawners

### ISSUE THREAD

**Issue by srnyxx** [OhTheDungeon/OhTheDungeon#31]
The torches in some dungeons (ex: Tower) completely disable spawners because of the way 1.18 changes monster spawning (they now require complete darkness to in order to spawn).

*For some reason my main account, @srnyx, is blocked from making issues, so I'm using my alt. Please unblock my main account, I have no idea why it's even blocked I haven't made a single issue on this repository until now.*

**Comment by sphings79** [comment]
Not only the torches. Also the lightning blocks In the dungeon with the nether look. Light level is up to 12.

**Comment by OhTheDungeon** [comment]
The spawner has NBT tag which sets the `block_light_limit` rule.
Unfortunately due to a MC bug (https://bugs.mojang.com/browse/MC-245774), it doesn't work.
Most likely it will be fixed in future minecraft version

**Comment by sphings79** [comment]
Within the mojang ticket, the opener wanted to let the ticket gets closed ause the command is wrong for 1.18.
Have a look: https://bugs.mojang.com/browse/MC-245774

**Comment by srnyx** [comment]
For a temporary fix, I'm using [SpawnerControl](https://www.spigotmc.org/resources/spawnercontrol.98872), which weirdly released the day I made this issue.

**Comment by OhTheDungeon** [comment]
Will fix in future
