### ISSUE TITLE
Lag issues in 1.18.1 get The server has not responded for 10 seconds!

### ISSUE THREAD

**Issue by broken1arrow** [OhTheDungeon/OhTheDungeon#33]
We have a pretty fast computer with pretty new intel i3-9100 and 32GB ram

25 chunk distance. 

https://timings.aikar.co/?id=62c430c8ff9b486ab1739a67601d6581
https://pastebin.com/CRtcdPzf

**Comment by OhTheDungeon** [comment]
We can do nothing. The 1.18 world gen is 4.7x slower in our benchmark (maybe due to the increase of terrain height or the cave structure).UNLESS MOJANG fixs.that, we can do nothing

**Comment by broken1arrow** [comment]
> We can do nothing. The 1.18 world gen is 4.7x slower in our benchmark (maybe due to the increase of terrain height or the cave structure).UNLESS MOJANG fixs.that, we can do nothing

Alright. Yeah is more blocks to check in 1.18 now (even air blocks).

I don't know if your plugin can use or benefits use async methods for chunks? 

Other option I missing (or not find it). Is then option to set chance dungeon spawn not only chunks apart (it spawn lot closer when use default 22 settings).

**Comment by OhTheDungeon** [comment]
https://github.com/OhTheDungeon/OhTheDungeon/blob/main/src/otd/lib/async/AsyncWorldEditor.java
We already use the async chunk gen.

I also notice that you are using a i3 processor with only 4 cpres. THIS IS NOT GOOD. check this paper patch:
https://github.com/PaperMC/Paper/blob/master/patches/server/0777-Reduce-worldgen-thread-worker-count-for-low-core-cou.patch

For cpu with 4 cores, it will use only 2 workers for world gen. In this case, async chunk load will be slower than sync way

**Comment by broken1arrow** [comment]
> https://github.com/OhTheDungeon/OhTheDungeon/blob/main/src/otd/lib/async/AsyncWorldEditor.java We already use the async chunk gen.
> 
> I also notice that you are using a i3 processor with only 4 cpres. THIS IS NOT GOOD. check this paper patch: https://github.com/PaperMC/Paper/blob/master/patches/server/0777-Reduce-worldgen-thread-worker-count-for-low-core-cou.patch
> 
> For cpu with 4 cores, it will use only 2 workers for world gen. In this case, async chunk load will be slower than sync way

And the function I mentioned below? 

We host server self, so upgraded is not planned  right now.
