### ISSUE TITLE
Crash server with Exception in server tick loop 1.18.1

### ISSUE THREAD

**Issue by Diablolend** [OhTheDungeon/OhTheDungeon#34]
Hello!
I moved my server from 1.17.1 to 1.18.1. I found a crash on the border of old and new chunks. All plugins were removed except "Oh The Dungeon", because suspicions fell on him. And so it turned out.
The Paper has been updated to the latest version, but I tried early builds as well.

[crash-2022-01-08_14.54.43-server.txt](https://github.com/OhTheDungeon/OhTheDungeon/files/7833005/crash-2022-01-08_14.54.43-server.txt)

**Comment by OhTheDungeon** [comment]
otd is not in stacktrace. Report this to paper
