### ISSUE TITLE
Natural Spawn Frequency

### ISSUE THREAD

**Issue by gazpachoking** [OhTheDungeon/OhTheDungeon#35]
Is there a way to turn down the natural spawn frequency of the dungeons? We enabled the Lich tower on our server, and this is what the first exploration of new land looked like:
![image](https://user-images.githubusercontent.com/187133/149172074-c7ccc7bb-785f-45f2-ac66-01d357085177.png)

**Comment by OhTheDungeon** [comment]
Check the spawn chunk distance in the config gui

**Comment by gazpachoking** [comment]
Is this the setting you mean? I can raise it, but it seems these are a lot closer that 22 chunks between dungeons already.
![image](https://user-images.githubusercontent.com/187133/149192097-0ac7d7cc-6a3c-422c-bd35-3bc3bf715d9c.png)

**Comment by OhTheDungeon** [comment]
As it's said, 'average'

**Comment by gazpachoking** [comment]
I just did a couple distance calculations, and I guess they are much closer to 22 chunks apart than I thought. Thanks for pointing me to the right setting. 👍 I would suggest turning that default value up, because these seem way close together.
