### ISSUE TITLE
Generation issue

### ISSUE THREAD

**Issue by srnyx** [OhTheDungeon/OhTheDungeon#36]
Not sure if this can be fixed:
![image](https://user-images.githubusercontent.com/25808801/150459896-42b98199-609f-4c9a-bd28-564f35d656f2.png)
![image](https://user-images.githubusercontent.com/25808801/150459924-f0ff6737-b5aa-4597-992a-1be641b63bce.png)

**Comment by OhTheDungeon** [comment]
Won't fix
