### ISSUE TITLE
Upon upgrading to 1.18, all current dunegons were reset or filled with stone

### ISSUE THREAD

**Issue by MrRazamataz** [OhTheDungeon/OhTheDungeon#37]
**Version**
1. Purpur: `git-Purpur-1538 (MC: 1.18.1)*`
2. Plugin Version: `Oh_the_dungeons_youll_go version 15_Minor_Cold_2022`

**Describe the bug**
Dungeons in old chunks have been reset and anything built in them has been lost

**To Reproduce**
Steps to reproduce the behaviour:

Steps followed to upgrade from 1.17:
1. Run `--forceUpgrade` on 1.17.
2. Replace server and plugin jars
3. Start on 1.18. 
4. See dungeons reset or filled with stone.

**Expected behaviour**
For the old dungeons to not be reset or filled with stone.

**Comment by OhTheDungeon** [comment]
Test with a upgrade from 1.17.1 to 1.18.1, nothing broken
OTD won't do anything for container update (after dungeon creation, they will just work as vanilla container)

Here's the thing you should do for upgrade
1. Using spigot during upgrade flow
2. Remove all plugins during upgrading
3. After upgrade finish, add the plugins back and change to other severs like paper
