### ISSUE TITLE
No experience on Dungeon spawner..

### ISSUE THREAD

**Issue by Jordyeasy** [OhTheDungeon/OhTheDungeon#38]
Hi man ! I hope everything is ok for you !
I'm really sorry to annoy you with a possible stupide question...
But can we have experience and loot from the mobs who spawn in dungeons (from the spawners) ? I would like to let my players make big xp farm from the dungeons... I searched everywhere on the file but found nothing.
Have a nice day ! Take care of you

**Comment by OhTheDungeon** [comment]
Check the config gui first...
![scs](https://user-images.githubusercontent.com/63266533/152751229-d2df542c-0057-447c-a2b8-b9d9f99656dd.JPG)

**Comment by Jordyeasy** [comment]
I'm so sorry, thanks a lot <3
