### ISSUE TITLE
Major Incompatibility w/ Iris World Generator

### ISSUE THREAD

**Issue by ktcrow** [OhTheDungeon/OhTheDungeon#39]
**Version**
1. Purpur Build 1547
2. OTD version 16_New_Year_2022

**Describe the bug**
So, I am well aware this is NOT a bug with OTD, in fact, this plugin works perfectly.  The problem I am having is a compatibility issue with a world generator called Iris.  In 1.16.5, I used Iris and OTD in tandem to create a custom post-End dimension full of dungeons to explore; they worked fantastically together and my players LOVED it.  Now, upgrading to 1.18.1, the new height limits seem to be causing a clash.

As I understand it, Iris generates chunks using 0 as the lowest point and then lowers them by 60 blocks so that it falls within the new Y-coordinate boundaries.  The problem arises when I add OTD to the mix.  All the dungeons are floating 60 blocks in the air!  I was wondering if there is some way to lower the dungeons by 60 similarly, or perhaps automatically generate the AFTER chunk generation is complete?

I have been in touch with Iris support and they told me that they can't do anything to fix this on their end and that I should be in touch with the OTD support.

**To Reproduce**
Create an Iris world, turn on natural generation with OTD, generate new chunks in the Iris world.

**Expected behavior**
Ideally, I would like the dungeons to just spawn in the right place as chunks generate.  However, a workaround might be to create the Iris world, pregenerate it, set a world border so that no new chunks could load, and then generate the dungeons afterwards at the correct height.

**Screenshots**
![otd problem 1](https://user-images.githubusercontent.com/49538849/152898906-c0a45174-c955-400c-90b9-c04cc5c9b5fa.png)
![otd problem 2](https://user-images.githubusercontent.com/49538849/152898914-2bf8f4cd-6d7a-45b4-ae3d-6f6ab1cc8f8b.png)

**Comment by OhTheDungeon** [comment]
I didn't see a ticket opened on Iris's issue tracker. I need to see a ticket first to get their basic analysis before digging into it

**Comment by ktcrow** [comment]
I consulted with them on their Discord support channel, they basically told me that they can't do anything for me.  I will create a ticket over there after I'm done with work and link it here.  My apologies.

**Comment by ktcrow** [comment]
Alright, I opened a ticket with Iris. https://github.com/IrisDimensions/overworld/issues/259

**Comment by OhTheDungeon** [comment]
A new release is under verification now. Hope it will fix this issue

**Comment by ArMiN231** [comment]
> A new release is under verification now. Hope it will fix this issue

Any news about that?

**Comment by OhTheDungeon** [comment]
Still need 1 or 2 more days

**Comment by OhTheDungeon** [comment]
Fixed in `17_Rain_Water_2022`

Please change the `worldParameter` in the world setting gui of otd.
For generator like Iris, try to set `bottom` to `-59` and `sealevel` to `0`
