### ISSUE TITLE
Give option to turn off "User_PI_Suggest" upon Login

### ISSUE THREAD

**Issue by Yakut58** [OhTheDungeon/OhTheDungeon#41]
**Version**
1. Spigot Version 1.18.1
2. Plugin Version 16_New_Year_2022

**Describe the bug**
There should be an option to disable messages upon login (example: Disable User_PI_Suggest)

**To Reproduce**
Start logging in after setting up the plugin

**Expected behavior**
As mentioned in description
problem before.

My reasoning is is that this message doesnt need to appear on every log in so having a simple turn off/turn on switch in the config would be very convenient

**Comment by OhTheDungeon** [comment]
Would fix in next release

**Comment by OhTheDungeon** [comment]
Fixed in `17_Rain_Water_2022`

**Comment by LoJoSho** [comment]
Hey, just came across this and noticed that there is still no option in the configuration to disable this. Where would we find this configuration setting?
