### ISSUE TITLE
Spawner destroy on TNT or Creeper explosion if set to not destroyable

### ISSUE THREAD

**Issue by sphings79** [OhTheDungeon/OhTheDungeon#43]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. This server is running Paper version git-Paper-198 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: c50fc3a)
2. 16_New_Year_2022
(Remember, `latest` is not a valid version)

**Describe the bug**
Spawner destroy on TNT or Creeper explosion if set to not destroyable

**To Reproduce**
Set spawner to not destoyable and let a creeper blew up or use tnt.

**Expected behavior**
spawner should stay

**Screenshots**
i think its not needed

**Comment by OhTheDungeon** [comment]
Fixed in `17_Rain_Water_2022`
