### ISSUE TITLE
More API events

### ISSUE THREAD

**Issue by PikaMug** [OhTheDungeon/OhTheDungeon#44]
Could we get some more events for things that occur within a dungeon? Mob kills, player death, etc.

**Comment by OhTheDungeon** [comment]
https://github.com/OhTheDungeon/OhTheDungeon/blob/d2819877869fbe772544563756f041a00967a74a/src/otd/listener/SpawnerListener.java#L254-L255

This should meet your needs for now

**Comment by OhTheDungeon** [comment]
In `17_Insects_Awaken_2022`, we add some new API for this:
otd.api.MobManager
otd.api.SpawnerManager

You can call these in the normal spigot event to see if they are triggered by OTD

**Comment by PikaMug** [comment]
@OhTheDungeon Great! Looking forward to seeing those classes on Github.
