### ISSUE TITLE
RogueLike Dungeon

### ISSUE THREAD

**Issue by Maxence621** [OhTheDungeon/OhTheDungeon#46]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1.18
i know "latest" is not a correct answer, but i can't find the version , it's the latest on spigot (i downloaded it the 21/02/2022)

**Describe the bug**
There is no minimum amount of loot in the dungeon "RogueLike" unlike all other dungeons, which make it more difficult to setup

**To Reproduce**
write ./otd , put a loot in the Roguelike dungeon, place the roguelike dungeon, see there is always the maximum ammount of item in chest.

**Expected behavior**
I would expect it to be more easier to setup like all the other dungeon , because it's not very balanced since the maximum amount is always in the chest, there is no "between 0 and 15" for example, it will alwyas be 15.

**Comment by OhTheDungeon** [comment]
Roguelike uses its own way to control loots. It will based on its own weight choice system to decide the loot chests content. (so that it will provide a roguelike experience)

For the item counts, you can always control it by setting different nodes. Like 3 nodes, each node with 5 items, which makes you control the amount of loots.

**Comment by Maxence621** [comment]
okay i kind of understand, but it would be so great if you could add a
button that could turn off / on this and turn it into the same system as
other dungeons, with a min amount and a max amount to put for each items,
bc for me it's hard to setup :(

Le mar. 22 févr. 2022 à 19:52, OhTheDungeon ***@***.***> a
écrit :
