### ISSUE TITLE
Update notification after update to latest version

### ISSUE THREAD

**Issue by mkhansen981017** [OhTheDungeon/OhTheDungeon#47]
**Version**
![image](https://user-images.githubusercontent.com/13025353/155836052-7359a140-8563-48e7-bb88-cbbb014d7c6a.png)

**Describe the bug**
It seems that even tho i have updated the plugin to the latest version, it still thinks its outdated as i get a OP message saying there is an update available

**To Reproduce**
Happens after every attempt to update to the latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/13025353/155836023-98d1e175-5617-476b-a124-54a9645a6069.png)

**Comment by OhTheDungeon** [comment]
Will fix in net release

**Comment by OhTheDungeon** [comment]
Fixed in `17_Insects_Awaken_2022`
