### ISSUE TITLE
Dungeon Settings Seem To Reset

### ISSUE THREAD

**Issue by mkhansen981017** [OhTheDungeon/OhTheDungeon#48]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Spigot/Paper Version - 
![image](https://user-images.githubusercontent.com/13025353/155881441-479cc9b7-171d-439d-9a05-5e5b7f1b42c2.png)

2. Plugin Version - 17_Rain Water_2022

**Describe the bug**
Not sure what the connection is or how to recreate the issue. But my issue is that sometimes when i want to regenerate a world for testing purposes. All the configurations ive created for dungeon spawns seem to completely reset to the default state of the plugin installation. im regenerating the world by first going to its region folder and deleting all region files that does not contain player bases. then i use chunky to generate the world in a set radius

**Comment by OhTheDungeon** [comment]
We cannot recreate this issue. Please provide more info and more details.
1. What's the name of your testing world
2. What's the step of your recreating the world? Plese provides the step one by one, like first close server, then do xxx
3. Provides the log file and the yml and db file in the plugin folder
