### ISSUE TITLE
MythicMobs support not working

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [OhTheDungeon/OhTheDungeon#49]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Spigot/Paper Version - Paper version git-Paper-"e04368045" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
2. Plugin Version - 17_Rain Water_2022
(Remember, `latest` is not a valid version)

**Describe the bug**
The bosses in the dungeons aren't hooking into MythicMobs.

**To Reproduce**
Switch to MythicMobs support

**Expected behavior**
The bosses within the dungeons are supposed to hook into MythicMobs.

**Screenshots**
![image](https://user-images.githubusercontent.com/57046530/155901192-b8f80ed1-c5e5-4f33-aafb-c5edff0a2782.png)

**Comment by RealHypnoticOcelot** [comment]
Unrelated, I'd love to see some sort of /locate feature for dungeons

**Comment by OhTheDungeon** [comment]
please upload your config.db file

**Comment by RealHypnoticOcelot** [comment]
[config.db.zip](https://github.com/OhTheDungeon/OhTheDungeon/files/8156866/config.db.zip)
Version 4.13.1-3de5637b
There is no file

**Comment by OhTheDungeon** [comment]
> [config.db.zip](https://github.com/OhTheDungeon/OhTheDungeon/files/8156866/config.db.zip) Version 4.13.1-3de5637b There is no file
> 
> sorry for the late response

Please read https://github.com/OhTheDungeon/OhTheDungeon/blob/main/OTD.pdf carefully.
You need to provide `otd_lich` file by yourself

**Comment by RealHypnoticOcelot** [comment]
oh, is there no preset boss?

**Comment by OhTheDungeon** [comment]
Built-in boss is `Vanilla`
