### ISSUE TITLE
redstone repeater missing in roguelike with the rocket chimneys. 

### ISSUE THREAD

**Issue by DanyGreaver** [OhTheDungeon/OhTheDungeon#5]
![image](https://user-images.githubusercontent.com/62079225/108666961-cd958280-74f1-11eb-9748-556a86521080.png)
![image](https://user-images.githubusercontent.com/62079225/108667315-61674e80-74f2-11eb-90f4-0d95d9095ee1.png)

The comparator output has a signal strength of 1 therefore it's not reaching the block with a wire of length 2. 
A repeater would do the job as shown in the screenshot. 
Also might add a few rockets in the dispensers on top, if you have some extra time. that one is very optional 

thank you very much for this amazing plugin. :)

**Comment by OhTheDungeon** [comment]
Fixed in 15.13

**Comment by broken1arrow** [comment]
> ![image](https://user-images.githubusercontent.com/62079225/108666961-cd958280-74f1-11eb-9748-556a86521080.png) ![image](https://user-images.githubusercontent.com/62079225/108667315-61674e80-74f2-11eb-90f4-0d95d9095ee1.png)
> 
> The comparator output has a signal strength of 1 therefore it's not reaching the block with a wire of length 2. A repeater would do the job as shown in the screenshot. Also might add a few rockets in the dispensers on top, if you have some extra time. that one is very optional
> 
> thank you very much for this amazing plugin. :)

Is not the idea it only fire when the hoe is chosen (so you get a random effect) ?  because that have signal strength of 3 (normal items have 1).

**Comment by broken1arrow** [comment]
Normally is it 8 sticks and one hoe inside the dropper.

**Comment by OhTheDungeon** [comment]
If that's the case I think next version will remove the repeator

**Comment by broken1arrow** [comment]
> If that's the case I think next version will remove the repeator

Yeah you can try it out self, so see it trigger random.

I think is pretty clever idea.
