### ISSUE TITLE
Error when placing Lich

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [OhTheDungeon/OhTheDungeon#50]
You SHOULD use English or Chinese in an issue report.
Make sure you use the diagnostic tools first (under /otd -> utils)
Version

Spigot/Paper Version - Paper version git-Paper-"e04368045" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugin Version - 17_Rain Water_2022
(Remember, latest is not a valid version)
Describe the bug
Can't /otd_place without error

To Reproduce
Attempt to place a Lich tower twice, (while switching worlds??? not sure if that's part of the error)

Expected behavior
Dungeon is supposed to place

Error

28.02 23:35:08 [Server] Server thread/INFO HypnoticOcelot issued server command: /otd_place lich
28.02 23:35:08 [Server] Server thread/ERROR null
28.02 23:35:08 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'otd_place' in plugin Oh_the_dungeons_youll_go v17_Rain Water_2022
28.02 23:35:08 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:08 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:09 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:09 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:09 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:09 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:09 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:09 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.02 23:35:09 [Server] INFO Caused by: java.lang.NullPointerException: Cannot read field "worldParameter" because "swc" is null
28.02 23:35:09 [Server] INFO at otd.util.ActualHeight.getHeight(ActualHeight.java:65) ~[?:?]
28.02 23:35:09 [Server] INFO at otd.commands.Otd_Place.onCommand(Otd_Place.java:183) ~[?:?]
28.02 23:35:09 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:09 [Server] INFO ... 19 more
28.02 23:35:18 [Server] Server thread/INFO Negative index in crash report handler (0/13)
28.02 23:35:18 [Server] Server thread/ERROR Failed to save chunk 6,0
28.02 23:35:18 [Server] INFO net.minecraft.server.v1_16_R3.ReportedException: Saving entity NBT
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.Entity.save(Entity.java:1777) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.Entity.a_(Entity.java:1638) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.Entity.d(Entity.java:1646) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:568) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:439) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerChunkMap.saveChunk(PlayerChunkMap.java:1518) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerChunkMap.saveIncrementally(PlayerChunkMap.java:888) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.ChunkProviderServer.saveIncrementally(ChunkProviderServer.java:726) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.WorldServer.saveIncrementally(WorldServer.java:1085) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1373) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
28.02 23:35:18 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.02 23:35:18 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by OhTheDungeon** [comment]
you didn't initialize the world config.
In `/otd`, click first icon, then chose the world you want to place lich tower, then close the gui

And after that you could properly place a dungeon

We'll add auto init for the config later
