### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by ErythroCraft** [OhTheDungeon/OhTheDungeon#52]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Spigot: spigot-api-1.18.2-R0.1-SNAPSHOT.jar
2. Plugin Version: 17_Insects_Awaken_2022

**Describe the bug**
Could not pass event EntityDeathEvent to Oh_the_dungeons_youll_go v17_Insects_Awaken_2022, 
caused by  java.lang.NoSuchMethodError 'boolean org.bukkit.event.entity.EntityDeathEvent.isCancelled()'

**To Reproduce**
Starting server 

**Expected behavior**
Not more. Please watch out the latest log file.

**LOG-FILE**
[latest - Kopie.log](https://github.com/OhTheDungeon/OhTheDungeon/files/8191041/latest.-.Kopie.log)

**Comment by OhTheDungeon** [comment]
`Make sure you use the diagnostic tools first (under /otd -> utils)`

**Comment by ErythroCraft** [comment]
sorry my misstake. 
The version actually is spigot-api-1.18.2-R0.1-SNAPSHOT

your plugin is actually on spigot-1.18.2-R0.1-SNAPSHOT
