### ISSUE TITLE
Small bug with the plugin EcoEchants.

### ISSUE THREAD

**Issue by TwiztedUnique** [OhTheDungeon/OhTheDungeon#53]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Spigot/Paper Version: Paper(Build 216) 1.18.1
2. Plugin Version: 17_Insects_Awaken_2022

**Describe the bug**
I have the plugin EcoEnchants which allows the custom enchant books to be able to generate across the world or obtainable from enchant tables and from regular villager trades, I did have to disable the generation of them for the time being to balance some enchants but some players started noticing that any custom enchant book still seems to generate in the loot chests of the dungeon world, I tested villagers and enchant tables and those seem to work as expected so no issues there

**To Reproduce**
Have EcoEnchants with config edited to disable the enchant books being generated on same server as otdyg and create a dungeon

**Expected behavior**
Normal enchantment books are fine but since some of the new enchants are a bit unbalanced if it could only generate the ones that are enabled in the EcoEnchants config or if disabled entirely then only normal enchant books like sharpness or smite could spawn in the chests

**Screenshots**
None

**Comment by OhTheDungeon** [comment]
You didn't say which dungeon type here but I guess you can only find them in `doomlike`.

You can try disable the built-in loottable for doomlike dungeon and then use your own loottable instead.

**Comment by OhTheDungeon** [comment]
Could you provide us the info in the previous reply?

**Comment by OhTheDungeon** [comment]
As we didn't get any reply here, closing this ticket now
