### ISSUE TITLE
MythicMobs not hooking in

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [OhTheDungeon/OhTheDungeon#54]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Spigot/Paper Version
**This server is running Paper version git-Paper-"e04368045" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Paper-"4e355c4" (MC: 1.18)**
3. Plugin Version
**17_Rain Water_2022**

**Describe the bug**
The game is supposed to spawn in the mythicmobs boss

**To Reproduce**
Place a Lich tower with mythicmobs enabled

**Expected behavior**
The game would spawn the custom boss

**Screenshots**
![image](https://user-images.githubusercontent.com/57046530/159176717-b4c7c36e-d966-41b3-b5ea-5951e7718211.png)
![image](https://user-images.githubusercontent.com/57046530/159176722-bd4d9a00-8895-4fa0-b286-f45dc5eadb34.png)

**Comment by OhTheDungeon** [comment]
I think in the previous ticket, I've told what should be provided. Since they are not here and we cannot get out what really happened, this will be marked as `invalid`

**Comment by RealHypnoticOcelot** [comment]
[config.db.zip](https://github.com/OhTheDungeon/OhTheDungeon/files/8312018/config.db.zip)
Version 4.13.1-3de5637b
[LichMob.yml.zip](https://github.com/OhTheDungeon/OhTheDungeon/files/8312017/LichMob.yml.zip)
https://mcpaste.io/1de08cc30e778655

**Comment by OhTheDungeon** [comment]
Like what I said previously, `Reopen it once you get everything ready`, otherwise we'll ignore this ticket.

Obviously you have some issues in your mythicmobs config, please solve them first.
You can try `/mm mobs spawn otd_lich_boss` and see if it could work or not.

And also I noticed that you report this to an old version. Please use latest version first as we already fix something there

**Comment by OhTheDungeon** [comment]
Please update to `17_Spring_Equinox_2022_P1` and use the diagnostic tools (under /otd -> utils)
