### ISSUE TITLE
DoomLike Dungeon - Loot not corresponding

### ISSUE THREAD

**Issue by Maxence621** [OhTheDungeon/OhTheDungeon#56]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
2. 2 version behind (idk where to find the correct version)
(Remember, `latest` is not a valid version)

**Describe the bug**
I have put some items in the "Configurable Loot" for the dungeon DoomLike, but after removing the "built-in loot", there is still a lot of loot that i didn't put in the config that appear.. ( i tried restarting server, reloading plugin etc..) , and after each test i place a new dungeon by the way

**To Reproduce**
Put some items in loot config of a dungeon

**Expected behavior**
I expected that it was going to work and not add more items

**Screenshots**
![2022-03-23_16 04 36](https://user-images.githubusercontent.com/48748900/159730546-c0cb6350-6f2e-4f41-a2a4-a29e2991b2dd.png)
![2022-03-23_16 04 43](https://user-images.githubusercontent.com/48748900/159730556-b6226e39-fa3f-4db8-bc3d-28c6fafe9496.png)

**Comment by OhTheDungeon** [comment]
Plugin version wasn't given out so we cannot do further debug. Please try to use the latest version on spigot.
Also we cannot recreate this issue with test env (new world, new config & only 1 plugins) so this will be marked as `invalid`.

Please first exclude the influence of other plugins & datapack first
