### ISSUE TITLE
Loot Gui bug

### ISSUE THREAD

**Issue by Maxence621** [OhTheDungeon/OhTheDungeon#58]
**Version**
1. Spigot/Paper Version **Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)**
2. Plugin Version **lastest wich is (if i'm right) 17_Spring_Equinox_2022_P1**

**Describe the bug**
So, when i add a loot in the chest gui, it doesn't pop in chest inside dnugeons when i put "Add Built-In loot" to disable.
Even when enable , it doesn't seem to pop in.
Also, i have find out that when i place a dungeon with the command, it "bug" the chest gui and remove every item you put, untill you do "/otd_reload"

Also, when i create a dungeon plot world, it doesn't respect the "Add Built-in loot" off.

**To Reproduce**
Put Built-in loots to off, add an item to a dungeon (like doomlike), then walk around and see all chest are empty

**Expected behavior**
I expected the loot chest gui to work

**Screenshots**
![2022-03-25_11 40 57](https://user-images.githubusercontent.com/48748900/160105894-4c5ea4a2-5472-49bb-9a70-f7c068be79a7.png)
![2022-03-25_11 41 00](https://user-images.githubusercontent.com/48748900/160105913-52c9b933-035c-4e94-86e7-2dbdae7c6a2b.png)
![2022-03-25_11 41 04](https://user-images.githubusercontent.com/48748900/160105933-d04244c4-1a09-43be-bf23-74500aa02472.png)
![2022-03-25_11 41 08](https://user-images.githubusercontent.com/48748900/160105949-764038be-df43-45f8-a171-5594e03b0191.png)
![2022-03-25_11 41 09](https://user-images.githubusercontent.com/48748900/160105965-c387099c-9566-4c5e-9ffa-63369ede1441.png)

**Comment by OhTheDungeon** [comment]
please upload your config

**Comment by Maxence621** [comment]
> please upload your config

what do you mean by config ?

**Comment by Maxence621** [comment]
> please upload your config

What do you mean by config ?

**Comment by OhTheDungeon** [comment]
config.db

**Comment by Maxence621** [comment]
[config.zip](https://github.com/OhTheDungeon/OhTheDungeon/files/8352177/config.zip)

**Comment by OhTheDungeon** [comment]
I didn't see you change the config of plot world. You only change the config of a test world and that won't affect what plot world looks like.

**Comment by OhTheDungeon** [comment]
` "normal" world and the loot not beeing inside chest`

Please restart your server and retry. In the log I saw more than 1 ops were editing the loot. We only support 1 user edit at the same time, otherwise there will be a conflict in commiting

**Comment by OhTheDungeon** [comment]
No, the thing is, you should never set the minimum amout to 0 here.
We will add a restriction for that in the next version. You can try to set the min value to 1 and see if it's work or not

**Comment by Maxence621** [comment]
> No, the thing is, you should never set the minimum amout to 0 here. We will add a restriction for that in the next version. You can try to set the min value to 1 and see if it's work or not

okay it fixed everything, thank you,  i'm really bad xD
(also, i know i've already talk to you about this, but it would be very nice if you could add a button to change the way the loot are generated in roguelike dungeon)
Anyway, very good job as always, keep like that and thank you for everything !
