### ISSUE TITLE
Draylar tower causes freezes and crashes while generating

### ISSUE THREAD

**Issue by BigScary** [OhTheDungeon/OhTheDungeon#59]
**Version**
1. Spigot/Paper Version Git-Paper-249, MC 1.18.2
2. Plugin Version 17_spring_equinox_2022_p1

**Describe the bug**
The server intermittently freezes (big lag, all players disconnect, console spam) and crashes (all players disconnect, crash logs generated). This problem immediately disappeared when I disabled Draylar Battle Tower from automatic generation. I still have roguelike, doomlike, and aether dungeons enabled and have not seen another incident for several hours now.

Example logs from both lag and crash instances:

https://pastebin.com/ck1pz5qV

**To Reproduce**
Steps to reproduce the behavior: Seems like players just need to be online and moving about. I assume their exploration triggers draylar to generate, which then freezes the server.

**Comment by OhTheDungeon** [comment]
`java.lang.IllegalStateException: Chunk not there when requested`

This is not a issue of this mod, it's purely a chunk/world generation issue in paper/vanilla
Possible reason is:
1. No `--forceUpgrade` before using the server map
2. MC-224893
3. Other unknown issue in paper
