### ISSUE TITLE
Plot and custom dungeons

### ISSUE THREAD

**Issue by JUSTCOOP** [OhTheDungeon/OhTheDungeon#62]
**Version**
1. Paper Version 1.18.2 (paper-1.18.2-283)
2. Plugin Version: 17_Spring_Equinox_2022_P1

**Describe the bug**
Failed to create a dungeon using custom dungeons. There is no possibility to select a custom section during the creation of the plot.

**To Reproduce**
1. I created custom dungeon using NBT structure file.
2. When I opened Plot section, I got an error (missing custom dungeon button).
3. Diagnostic Tools said there was no error.

**Expected behavior**
I expected to see option to generate custom dungeon using plot addon.

**Screenshots**
![21](https://user-images.githubusercontent.com/68376879/162976043-4e83f87b-2845-49db-a04f-21f2681b2b8f.png)

**Comment by OhTheDungeon** [comment]
Dungeon Plot section never supports custom dungeon
