### ISSUE TITLE
Item with NBT TAG

### ISSUE THREAD

**Issue by Maxence621** [OhTheDungeon/OhTheDungeon#63]
**Version**
1. Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)
2. 17_Spring_Equinox_2022_P1
(Remember, `latest` is not a valid version)

**Describe the bug**
All custom loot we add has a NBT TAG of "HideFlag:127", the problem is, because of this tag, most of all item you put in dungeons chest can't be stack up with "vanilla" items.

**To Reproduce**
Put any item you want in custom loot, then go take it from a chest and then see that it doesn't stack with vanilla ones.

**Expected behavior**
I expected that the custom loot you put in chest get the NBT TAG of the item, so if you put a vanilla item, it doesn't have NBT TAG

**Screenshots**

**Comment by OhTheDungeon** [comment]
Didn't get enough info about dungeon type and screenshot. Test with aether and nothing seems wrong.
Closing
