### ISSUE TITLE
Natural gen not sowrking

### ISSUE THREAD

**Issue by Minecraftgamer37** [OhTheDungeon/OhTheDungeon#69]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Spigot/Paper Version 1.18.2
2. Plugin Version 17_spring_equinox
(Remember, `latest` is not a valid version)

**Describe the bug**
Natural gen not working, Have been flying around my world for hours still no spawning of dungeons
**To Reproduce**
Enable natural spawning
**Expected behavior**
Spawning of dungeon
**Screenshots**

**Comment by OhTheDungeon** [comment]
1. whats the output of diagnostic tool?
2. make sure you are visiting new generated chuck instead of already generated one

**Comment by OhTheDungeon** [comment]
closing as it works well in our environment, and for all other users

**Comment by Minecraftgamer37** [comment]
what is the other test server environments? I have been messing with mine all day and haven't gotten it to work. Log says otdfounds 0 issues but I see this 22.05 13:49:19 [Server] INFO [com.fastasyncworldedit.bukkit.listener.ChunkListener] [FAWE Tick Limiter] Detected and cancelled physics lag source at Location{world=CraftWorld{name=world},x=1049.0,y=72.0,z=352.0,pitch=0.0,yaw=0.0} 
I don't know if that as anything to with it,

**Comment by OhTheDungeon** [comment]
Test env is the spigot suggested one (https://github.com/SpigotMC/SpigotCraft)
You can build a small local server with only this plugin and see if it's going to generate
As what I said, it will only spawn in NEW generated chunk, so if you are using an exist world, go to the new generated area, like typing `/tp 50000 100 50000` and check the `log.txt`

**Comment by Minecraftgamer37** [comment]
Got it working then i reset my world and that seemed to break it, Yes i used the suggested one i meant more or less what plugins where on it, seemes like it worked after i installed protocol lib, but then i reset the world to actually have it populate more.  I get spammed with Chunk wait task info in otd_dungeon, Im going to try resetting my server again fully and put in only fawe, otd, vault, protocol lib.
