### ISSUE TITLE
Chunk not there when requested

### ISSUE THREAD

**Issue by FishOwO** [OhTheDungeon/OhTheDungeon#70]
My diagnostic tools does not show any error.

When this thing happens, it makes the whole server crash.

And this is the crash report when server crashes.
[crash-2022-05-22_21.23.56-server.txt](https://github.com/OhTheDungeon/OhTheDungeon/files/8751137/crash-2022-05-22_21.23.56-server.txt)

還有這邊可以用中文對吧?

**Comment by OhTheDungeon** [comment]
请使用paper测试，purpur不能完整支持本插件的Paper async chunk API

**Comment by FishOwO** [comment]
> 请使用paper测试，purpur不能完整支持本插件的Paper async chunk API
[crash-2022-05-23_15.53.40-server.txt](https://github.com/OhTheDungeon/OhTheDungeon/files/8752986/crash-2022-05-23_15.53.40-server.txt)
我用了paper
但一樣的狀況還是發生了

**Comment by OhTheDungeon** [comment]
你是用的旧存档升级到1.18?升级时有用forceupgrade参数吗?
