### ISSUE TITLE
Plugin not enabling EcoBosses even though it is installed.

### ISSUE THREAD

**Issue by NickAwrist** [OhTheDungeon/OhTheDungeon#73]
**Version**
1. PaperMC-8 1.19
2. version 19_Grain_in_Ear_P1

**Describe the bug**
EcoBosses is not being detected. I have both EcoBosses and OTD installed, but in the console, it says EcoBosses is not detected.

**To Reproduce**
Start server with both plugins 

**Expected behavior**
OTD recognizes EcoBosses and enables Boss features on startup

**Screenshots**
16.06 15:33:42 [Server] INFO Loaded EcoBosses

16.06 15:33:43 [Server] INFO [Oh The Dungeons Youll Go] EcoBosses not installed, will disable BossPlugin EcoBosses features

**Comment by NickAwrist** [comment]
8.46.0

**Comment by OhTheDungeon** [comment]
[OhTheDungeonsYoullGo-19_Grain_in_Ear_P2.zip](https://github.com/OhTheDungeon/OhTheDungeon/files/8934128/OhTheDungeonsYoullGo-19_Grain_in_Ear_P2.zip)
Could you try this version?

**Comment by NickAwrist** [comment]
Using the P2 version, I still got the same issue.

**Comment by OhTheDungeon** [comment]
unfortunately, I doesnt own that one so I cannot test it by my self, and its hard to maintance that feature. We have to remove that feature
