### ISSUE TITLE
Massive lag in a dungeon that has a square hole

### ISSUE THREAD

**Issue by faustojc** [OhTheDungeon/OhTheDungeon#8]
When I was finding the dungeon and I found this dungeon, it has an entrance at the surface and a square hole.
This dungeon, whenever I loot at it, it makes my MC goes crazy in lagging. This is only the dungeon that makes my MC lag so hard.

Video link:
https://drive.google.com/file/d/1Kq93C99jVyaKGWvdHWMJMcoiKteXMzqy/view?usp=sharing

Processor: Core i5 10400
Server: Aternos

![Untitled](https://user-images.githubusercontent.com/61080389/120314582-3e3a0100-c290-11eb-8e7a-03eab4e731ce.png)

**Comment by OhTheDungeon** [comment]
This fps dropping is on client side. Mojang will fix it in 1.17.
For now, you could temporarily fix it by using https://www.spigotmc.org/resources/mobspawnerfpslagfix.85357/
